### ISSUE TITLE
Scrollable dropdown

### ISSUE THREAD

**Issue by Eddolan** [jseppi/angular-dropdowns#60]
I am using this to make a dropdown for U.S. states and the issue is that with 50 options the dropdown is awkwardly large. Does angular-dropdowns have the ability to make the dropdowns smaller and scrollable ?

**Comment by jseppi** [comment]
You can add CSS rules to make the options container scrollable, for example:

```css
.dropdown {
  max-height: 400px;
  overflow-y: auto;
}
```
